name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  deployments: write
jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
      version_name: ${{ env.VERSION }}
    steps:
      # Get next version
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Create version string from tag (v1.0.0 -> 1.0.0)
      - name: Create version string
        run: |
          export TAG_NAME=${{ steps.release-drafter.outputs.tag_name }}
          echo "VERSION=${TAG_NAME:1}" >> $GITHUB_ENV

  publish_release:
    name: Release
    environment:
        name: prod
        url: https://crates.io/crates/junit2json
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [draft_release]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          # Use PAT for bypass ruleset guard when git push by cargo release
          # see: https://github.com/orgs/community/discussions/13836
          token: ${{ secrets.JUNIT2JSON_RS_PAT }}
      - name: Setup git author
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: Swatinem/rust-cache@v2
      - name: Setup cargo release
        run: cargo install cargo-release

      - name: Publish to crate.io
        run: cargo release --no-tag -vv --execute --no-confirm ${{ needs.draft_release.outputs.version_name }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
          tag: ${{ needs.draft_release.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_assets:
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: junit2json
          - os: ubuntu-20.04
            target: wasm32-wasi
            bin: junit2json.wasm
          - os: macos-latest
            target: x86_64-apple-darwin
            bin: junit2json
          - os: macos-latest
            target: aarch64-apple-darwin
            bin: junit2json
    name: Upload assets ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    if: github.event_name == 'workflow_dispatch'
    needs: ["draft_release", "publish_release"]
    steps:
    - uses: actions/checkout@v3
    - name: Setup rust build target
      run: rustup target add ${{ matrix.job.target }}

    - name: Build
      run: |
        if [[ "${{ matrix.job.target }}" == "wasm32-wasi" ]]; then
          cargo install cargo-wasi
          cargo wasi build --release --target ${{ matrix.job.target }}
        else
          cargo build --release --target ${{ matrix.job.target }}
        fi

    - name: Upload assets
      run: |
        ASSET_NAME="junit2json-rs-${{ needs.draft_release.outputs.version_name }}-${{ matrix.job.target}}.tar.gz"
        cp target/${{ matrix.job.target }}/release/${{ matrix.job.bin }} ./${{ matrix.job.bin }}
        tar -zcvf "${ASSET_NAME}" ${{ matrix.job.bin }}
        gh release upload ${{ needs.draft_release.outputs.tag_name }} "${ASSET_NAME}" --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
